### ISSUE TITLE
Prepare object sample for products which we expect to get from the API

### ISSUE THREAD

**Issue by esvyridov** [qaprosoft/infra-ui#11]
This section is dynamic
![image](https://user-images.githubusercontent.com/46542370/79456596-708a8f80-7ff7-11ea-85d6-9728a081b19b.png)

We should prepare an object interface like:
[
  {
    title: string;
    socials: [
      {
        link: string;
      }
    ] | undefined
  }
]

**Comment by dodgladot** [comment]
Array already exists: DataCards, that structure(may be with changes) we should get from request and set stateCards, next - set cards view(from stateCards). Or no?

**Comment by esvyridov** [comment]
@dodgladot Yep. But instead of sending real values let's prepare the sample object with types. Also we should think about if they send a full path to the logo or just a name of the logo.

**Comment by esvyridov** [comment]
[{
    name: string;
    icon: string;
    url: string;
}[]]
