### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by esvyridov** [qaprosoft/infra-ui#6]
Investigate these question for this issue:
- what we need to do to connect to twitter account
- is it possible to subscribe on new messages in twitter
- is it possible to subscribe on new messages in twitter which has certain hashtag
- how we can track if a twitter message was seen

Please write a short doc (better option) or comment this issue

**Comment by dodgladot** [comment]
1. Subscribe to account activity.
2. yes 
3. possible to subscribe on new messages in twitter which user_name, or user_id.
4. by clicking on notifications
more: [twitter-integration](https://github.com/qaprosoft/infra-ui/wiki/Twitter-integration)
